[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.mypy_cache
)/
'''

[tool.isort]
known_third_party = ["fastapi", "starlette"]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.pylint.messages_control]
disable = """
missing-module-docstring,missing-function-docstring,missing-class-docstring,
too-few-public-methods,invalid-name,logging-fstring-interpolation
"""
